spring:
  datasource:
    url: jdbc:h2:securitytest;MODE=mysql;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # none 으로 설정하면 테이블을 drop하고 다시 create 하는 작업을 안함.
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # in 쿼리 안의 개수를 뜻함. ex) item_id in (?, ?) 이런식으로 총 100개의 값까지 넣을 수 있다는 뜻
    open-in-view: false

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

## H2 Settings
#h2:
#  console:
#    enabled: true
#    path: /h2-console